services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    